#pragma once

#include "esp_adc/adc_oneshot.h" 
#include "driver/ledc.h"
#include "driver/i2c_master.h"

// THROTTLE CONFIGURATIONS
#define ACCELERATOR_SENSOR_CHANNEL ADC_CHANNEL_4 //GPIO 32
#define ACCELERATOR_SENSOR_ATTEN ADC_ATTEN_DB_12
#define ACCELERATOR_MINIMUM_TOLERANCE 0.99f
#define ACCELERATOR_MINIMUM_VOLTAGE 0.31f
#define ACCELERATOR_MAXIMUM_VOLTAGE 2.75f
#define ACCELERATOR_MAXIMUM_TOLERANCE 99.0f

// MOTOR CONFIGURATIONS
#define MOTOR_ACCELERATION_PWM_GPIO 27
#define MOTOR_ACCELERATION_PWM_CHANNEL LEDC_CHANNEL_0
#define MOTOR_DECELERATION_PWM_GPIO 26
#define MOTOR_DECELERATION_PWM_CHANNEL LEDC_CHANNEL_1

// SPEED SENSOR CONFIGURATIONS
#define SPEED_SENSOR_GPIO 25
#define SPEED_SENSOR_WHEEL_CIRCUMFERENCE_METERS 2.184f
#define SPEED_SENSOR_PULSES_PER_WHEEL_TURN 8.0f
#define SPEED_SENSOR_CALIBRATION_FACTOR 1.05f
#define SPEED_SENSOR_FILTER_ALPHA 0.15f
#define SPEED_SENSOR_MAX_SPEED_KMH 150.0f

// BRAKE SENSOR CONFIGURATIONS
#define BRAKE_SENSOR_GPIO 4
#define BRAKE_SENSOR_DEBOUNCE_TIME 50

// CLUTCH SENSOR CONFIGURATIONS
#define CLUTCH_SENSOR_GPIO 19
#define CLUCH_SENSOR_DEBOUNCE_TIME 50

//BTN CONTROL CONFIGURATIONS
#define BTN_CONTROL_GPIO 18
#define BTN_CONTROL_DEBOUNCE_TIME 180
#define BTN_CONTROL_CONFIRM_PRESS_TIME 1000

// PID CONFIGURATIONS
#define PID_KP 1.0f
#define PID_KI 0.0f
#define PID_KD 0.0f

// DISPLAY OLED CONFIGURATIONS
#define I2C_MASTER_SCL_GPIO         22
#define I2C_MASTER_SDA_GPIO         21
#define I2C_MASTER_NUM              I2C_NUM_0                   /*!< I2C port number for master dev */
#define I2C_MASTER_FREQ_HZ          100000                      /*!< I2C master clock frequency */
#define I2C_MASTER_ADDRESS          0x3C

// OTHER CONFIGURATIONS 
#define LED_GPIO 5
#define MINIMUM_SPEED_LIMIT 90